/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.18
 * Generated at: 2026-02-08 14:55:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;

public final class displayAssets_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Asset Management System</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        :root { --primary: #0078d4; --success: #28a745; --bg: #f4f7f6; }\r\n");
      out.write("        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: var(--bg); margin: 0; padding: 20px; }\r\n");
      out.write("        .container { max-width: 1000px; margin: auto; }\r\n");
      out.write("        \r\n");
      out.write("        /* Alert Box */\r\n");
      out.write("        .alert { padding: 15px; margin-bottom: 20px; border-radius: 4px; text-align: center; font-weight: bold; }\r\n");
      out.write("        .alert-success { background-color: #d4edda; color: #155724; border: 1px solid #c3e6cb; }\r\n");
      out.write("        \r\n");
      out.write("        /* Form Styling */\r\n");
      out.write("        .card { background: white; padding: 25px; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); margin-bottom: 30px; }\r\n");
      out.write("        .form-row { display: flex; gap: 10px; flex-wrap: wrap; }\r\n");
      out.write("        input, select { padding: 12px; border: 1px solid #ccc; border-radius: 4px; flex: 1; min-width: 150px; }\r\n");
      out.write("        button { background: var(--success); color: white; border: none; padding: 12px 25px; border-radius: 4px; cursor: pointer; transition: 0.3s; }\r\n");
      out.write("        button:hover { background: #218838; transform: translateY(-1px); }\r\n");
      out.write("\r\n");
      out.write("        /* Status Badges */\r\n");
      out.write("        .badge { padding: 5px 10px; border-radius: 12px; font-size: 0.85em; font-weight: bold; }\r\n");
      out.write("        .available { background: #e1f5fe; color: #0288d1; }\r\n");
      out.write("        .allocated { background: #fff3e0; color: #ef6c00; }\r\n");
      out.write("\r\n");
      out.write("        table { width: 100%; border-collapse: collapse; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }\r\n");
      out.write("        th { background: var(--primary); color: white; padding: 15px; text-align: left; }\r\n");
      out.write("        td { padding: 15px; border-bottom: 1px solid #eee; }\r\n");
      out.write("        tr:last-child td { border-bottom: none; }\r\n");
      out.write("        tr:hover { background-color: #f9f9f9; }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <h1 style=\"color: #333; text-align: center;\">🏢 Asset Core</h1>\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    ");
 if ("success".equals(request.getParameter("msg"))) { 
      out.write("\r\n");
      out.write("        <div class=\"alert alert-success\">✅ Asset added successfully to the inventory!</div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"card\">\r\n");
      out.write("        <h3>Register New Asset</h3>\r\n");
      out.write("        <form action=\"AssetServlet\" method=\"POST\" class=\"form-row\">\r\n");
      out.write("            <input type=\"text\" name=\"assetName\" placeholder=\"Asset Name (e.g., MacBook Pro)\" required>\r\n");
      out.write("            \r\n");
      out.write("            <select name=\"category\">\r\n");
      out.write("                <option value=\"Hardware\">Hardware</option>\r\n");
      out.write("                <option value=\"Software\">Software</option>\r\n");
      out.write("                <option value=\"Network\">Network</option>\r\n");
      out.write("            </select>\r\n");
      out.write("\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("            <select name=\"status\">\r\n");
      out.write("                <option value=\"Available\">Available</option>\r\n");
      out.write("                <option value=\"Allocated\">Allocated</option>\r\n");
      out.write("                <option value=\"Maintenance\">Maintenance</option>\r\n");
      out.write("            </select>\r\n");
      out.write("\r\n");
      out.write("            <button type=\"submit\">Add to Records</button>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <table>\r\n");
      out.write("        <thead>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th>ID</th>\r\n");
      out.write("                <th>Asset Name</th>\r\n");
      out.write("                <th>Category</th>\r\n");
      out.write("                <th>Status</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </thead>\r\n");
      out.write("        <tbody>\r\n");
      out.write("        ");
 
            List<Map<String, String>> assets = (List<Map<String, String>>) request.getAttribute("assets");
            if (assets != null && !assets.isEmpty()) {
                for (Map<String, String> asset : assets) {
                    String statusClass = asset.get("status").toLowerCase();
        
      out.write("\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>#");
      out.print( asset.get("id") );
      out.write("</td>\r\n");
      out.write("            <td style=\"font-weight: 500;\">");
      out.print( asset.get("name") );
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print( asset.get("category") );
      out.write("</td>\r\n");
      out.write("            <td>\r\n");
      out.write("                <span class=\"badge ");
      out.print( statusClass );
      out.write('"');
      out.write('>');
      out.print( asset.get("status") );
      out.write("</span>\r\n");
      out.write("            </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        ");
 
                }
            } else {
        
      out.write("\r\n");
      out.write("        <tr><td colspan=\"4\" style=\"text-align:center; color: #888;\">No assets found. Start by adding one above.</td></tr>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        </tbody>\r\n");
      out.write("    </table>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
